### PR TITLE
Hack to make Definition visible in the HTML documentation

### PR DESCRIPTION
**Pull request by AndreasLoow**
Workaround for issue #238

### CODE REVIEW

**Comment by AndreasLoow** [comment]
Hm, bossLib.new_specification is actually defined as pairLib.new_specification, but maybe the documentation still should say Theory.Definition.new_specification?

**Comment by xrchz** [comment]
I think whatever documentation is given for the (presumably non-existent) `Theory.Definition.new_specification` should instead be given for `pairLib.new_specification`.

**Comment by AndreasLoow** [comment]
I think saying something short about the relation between `Theory.Definition.new_specification`, `Theory.Definition.gen_new_specification` and `pairLib.new_specification` would be helpful. More concretely, if `pairLib.new_specification` is meant to supersede `Theory.Definition.new_specification`, then saying that as the documentation for the latter function would be helpful in my opinion (in combination with moving the documentation as suggested).

**Comment by mn200** [comment]
I think this is probably an improvement on what we had, so I don't want to let the perfect be the enemy of the good.

**Pull request merged**
