### PR TITLE
Borel and Lebesgue measure spaces (and their equivalence on Borel sets)

### PR DESCRIPTION
**Pull request by binghe**
Hi,

this huge PR continues #774 and finally resolved a big unresolved issue in #735 (The new HOL-Probability based on [0,+Inf]-measure theory) where I didn't finish the construction of Borel and Lebesgue measure spaces with the household measure (i.e. length of intervals).  After this PR, HOL's probability-related code will be in the *release* status, all future changes should be purely additional. Again, I merged a lot of code from HVG Concordia, but at least half of new scripts were newly proven by myself without referring to any other work (there's no identical theorems in Isabelle, Mizar or HOL Light).

Recall in #774, we have the Borel set generated as the smallest σ-algebra containing all open sets in `univ(:real)`:

```
   [borel]  Definition      
      ⊢ borel = sigma 𝕌(:real) {s | open s}
```

Now consider right open (left closed) interval on `univ(:real)` and the set of all such intervals (the name `right_open_interval` was learnt from MML, Mizar Math Lib), we may give it a "measure" as the length of such intervals, called `lambda0`:

```
   [right_open_interval]  Definition      
      ⊢ ∀a b. right_open_interval a b = {x | a ≤ x ∧ x < b}
   
   [right_open_intervals]  Definition
      ⊢ right_open_intervals = (𝕌(:real),{right_open_interval a b | T})

   [lambda0_def]  Definition      
      ⊢ ∀a b. a ≤ b ⇒ lambda0 (right_open_interval a b) = Normal (b − a)
```

This household measure `lambda0`, together with `borel`, forms a premeasure space `Abbrev lborel0 = (space borel, sets borel, lambda0)`.  Below is the most common way in textbooks (e.g. [1,2]) for constructing a Borel measure space:

  1. prove that, the set of all right open intervals form a semi-ring, and the smallest σ-algebra generated from right open intervals is also the borel set:

```
   [right_open_intervals_semiring]  Theorem      
      ⊢ semiring right_open_intervals

   [right_open_intervals_sigma_borel]  Theorem      
      ⊢ sigma (space right_open_intervals) (subsets right_open_intervals) = borel
```

  2. prove that, `lborel0` is positive, additive, subadditive, finite additive, and finally a premeasure (= positive + countably_additive):

```
   [lborel0_positive]  Theorem
      ⊢ positive lborel0

   [lborel0_additive]  Theorem
      ⊢ additive lborel0

   [lborel0_subadditive]  Theorem    
      ⊢ subadditive lborel0
   
   [lborel0_finite_additive]  Theorem
      ⊢ finite_additive lborel0
   
   [lborel0_premeasure]  Theorem
      ⊢ premeasure lborel0
```

 The proof of "lborel0_finite_additive" completes by induction on the number of intervals and "lborel0_additive", but to finish the proof I have to use `sortingTheory` to sort all non-empty (djsjoint) intervals so that the first `n-1` of them still form a valid right open intervals The proof of "lborel0_premeasure" requires the following form of the "Heine-Borel finite covering theorem", provided by `real_topologyTheory`, to help crossing the barriers from "(countable) infinity" to "finiteness":

```
   [COMPACT_IMP_HEINE_BOREL]  Theorem
      ⊢ ∀s.
            compact s ⇒
            ∀f.
                (∀t. t ∈ f ⇒ open t) ∧ s ⊆ BIGUNION f ⇒
                ∃f'. f' ⊆ f ∧ FINITE f' ∧ s ⊆ BIGUNION f'
```

  3. By `measureTheory.CARATHEODORY_SEMIRING` (Carathéodory's Extension Theorem, the semiring version) that I proved before, there exists an extension of `lborel0`, named `lborel` which is a real measure space with borel sets: (`Abbrev lambda = measure lborel0`)

```
   [lborel_def]  Definition
      ⊢ (∀s. s ∈ subsets right_open_intervals ⇒ lambda s = lambda0 s) ∧
        (m_space lborel,measurable_sets lborel) = borel ∧
        measure_space lborel
```

Once we get this measure space, it's immediate that, the measure of right-open intervals is still the desired one. But what's more important, the measure of singleton and open/closed intervals can also be proven (easily):

```
   [lambda_prop]  Theorem      
      ⊢ ∀a b. a ≤ b ⇒ lambda (right_open_interval a b) = Normal (b − a)

   [lambda_sing]  Theorem      
      ⊢ ∀c. lambda {c} = 0

   [lambda_open_interval]  Theorem      
      ⊢ ∀a b. a ≤ b ⇒ lambda (interval (a,b)) = Normal (b − a)

   [lambda_closed_interval]  Theorem     
      ⊢ ∀a b. a ≤ b ⇒ lambda (interval [(a,b)]) = Normal (b − a)
```

However, it's well known that, the above `lborel` is not complete, i.e., if for non-empty set `s` we have `lambda s = 0`, it's not that true that all subsets of `s` has also zero measure (because some of them may not be Borel sets at all!)  To get a complete measure space with all Lebesgue-measurable sets, we can define it directly by Henstock-Kurzweil (gauge) interval (`integrationTheory`) (this part is ported and edited from HVG's `lebesgue_measure_hvgTheory`)

```
   [lebesgue_def]  Definition
      ⊢ lebesgue =
        (𝕌(:real),{A | ∀n. indicator A integrable_on line n},
         (λA. sup {Normal (integral (line n) (indicator A)) | n ∈ 𝕌(:num)}))
```

Using theorems of `integrationTheory`, we can prove that, the above definition indeed defines a σ-algebra and measure space, and Lebesgue measure on closed intervals:

```
   [sigma_algebra_lebesgue]  Theorem
      ⊢ sigma_algebra (𝕌(:real),{A | ∀n. indicator A integrable_on line n})

   [measure_space_lebesgue]  Theorem      
      ⊢ measure_space lebesgue

   [lebesgue_closed_interval]  Theorem      
      ⊢ ∀a b. a ≤ b ⇒ measure lebesgue (interval [(a,b)]) = Normal (b − a)
```

Now comes the relationship between `lborel` and `lebesgue`, which have two very different definitions.  In fact, all Borel-measurable sets are contained in all Lebesgue-measurable sets, and any borel-measurable function is also a Lebesgue-measurable function:

```
   [lborel_subset_lebesgue]  Theorem
      ⊢ measurable_sets lborel ⊆ measurable_sets lebesgue

   [borel_imp_lebesgue_sets]  Theorem      
      ⊢ ∀s. s ∈ subsets borel ⇒ s ∈ measurable_sets lebesgue

   [borel_imp_lebesgue_measurable]  Theorem
      
      ⊢ ∀f.
            f ∈ borel_measurable (space borel,subsets borel) ⇒
            f ∈
            borel_measurable (m_space lebesgue,measurable_sets lebesgue)
```

Finally, by `measureTheory.UNIQUENESS_OF_MEASURE` (the uniqueness of measure for σ-finite measure spaces) that I ever proved, the two measure spaces `lborel` and `lebesgue` actually coincide on Borel sets:

```
   [lambda_eq_lebesgue]  Theorem   
      ⊢ ∀s. s ∈ subsets borel ⇒ lambda s = measure lebesgue s

   [lebesgue_eq_lambda]  Theorem      
      ⊢ ∀s. s ∈ subsets borel ⇒ measure lebesgue s = lambda s
```

As an easy application, the Lebesgue measure of open intervals can be derived directly from the corresponding results of `lborel` without using anything from `integrationTheory` and "lebesgue_def" itself:

```
   [lebesgue_open_interval]  Theorem      
      ⊢ ∀a b. a ≤ b ⇒ measure lebesgue (interval (a,b)) = Normal (b − a)
```

All my changes in this PR are directly or indirectly related with the above results, except for the following elegant and difficult result about borel-measurable sets, ported from HVG's work:

```
   [IN_MEASURABLE_BOREL_TIMES]  Theorem
      
      ⊢ ∀m f g h.
            measure_space m ∧
            f ∈ Borel_measurable (m_space m,measurable_sets m) ∧
            g ∈ Borel_measurable (m_space m,measurable_sets m) ∧
            (∀x. x ∈ m_space m ⇒ h x = f x * g x) ⇒
            h ∈ Borel_measurable (m_space m,measurable_sets m)
```

Some TODO work for the future:

  1. Prove that `lebesgue` is indeed a complete measure space.
  2. Replace the `SUBSET` in "lborel_subset_lebesgue" by `PSUBSET`, i.e. to show that there exists Lebesgue-measure but not Borel-measurable sets.  (This result requires the Axiom of Choice (AC), but I'm not sure if Higher Order Logic implies AC or not...)

Now `borelTheory` depends on `real_borelTheory`. For the first time, the previous ported (from HOL Light) `integrationTheory` is deeply used in HOL's probability formalization.   The whole work combines the best related work from HOL Light and Isabelle, and work by HVG group and myself. It closely aligns with modern textbooks, yet still minimizing the dependencies, thus suitable also for students who is learning measure and probability theories.

Best Regards,

Chun Tian

[1] Schilling, R.L.: Measures, Integrals and Martingales (2nd Edition). Cambridge University Press (2017).
[2] Chung, K.L.: A Course in Probability Theory. Academic Press (2001).

2020-02-01 01 10 25 pm

### CODE REVIEW

**Comment by binghe** [comment]
Additional notes:

  1. in `iterateTheory` there was a version of `ITSET` conflicting with `pred_set$ITSET`. I couldn't easily prove their equivalences. Since it's only needed locally, I have renamed it to `ITSET'`:

```
   [ITSET']  Definition     
      ⊢ ∀f s b.
            ITSET' f s b =
            (@g.
                 g ∅ = b ∧
                 ∀x s.
                     FINITE s ⇒
                     g (x INSERT s) = if x ∈ s then g s else f x (g s)) s
```

  2. To prevent name conflicts between definitions of Lebesgue and Henstock-Kurzweil (gauge) integrations, now I have renamed their `integral`, to `L_integral` and `HK_integral` and then overload them on the same name: (this change doesn't affect any existing proof, the changes for Lebesgue integral will be in next PR.)

```
Definition integral :
    HK_integral i f = @y. (f has_integral y) i
End

val _ = overload_on ("integral", ``HK_integral``);
```

**Comment by binghe** [comment]
Additional notes: I have renamed any theorems ported from HVG's `lebesgue_measure_hvgTheory`. For HVG people, to know the mapping between old and new theorem names, the best way is to run `grep "was: " *Script.sml` in `<holdir>/src/probability` and get such a list:

```
borelScript.sml:val IN_MEASURABLE_BOREL_IMP_BOREL = store_thm ((* was: borel_IMP_Borel *)
borelScript.sml:Theorem integral_one : (* was: MEASURE_HOLLIGHT_EQ_ISABELLE *)
borelScript.sml:Theorem in_sets_lebesgue : (* was: lebesgueI *)
borelScript.sml:Theorem limseq_indicator_BIGUNION : (* was: LIMSEQ_indicator_UN *)
borelScript.sml:Theorem in_sets_lebesgue_imp : (* was: lebesgueD *)
borelScript.sml:Theorem borel_imp_lebesgue_sets : (* was: lebesgueI_borel *)
borelScript.sml:Theorem borel_imp_lebesgue_measurable : (* was: borel_measurable_lebesgueI *)
borelScript.sml:Theorem negligible_in_sets_lebesgue : (* was: lebesgueI_negligible *)
borelScript.sml:Theorem lebesgue_negligible : (* was: lmeasure_eq_0 *)
borelScript.sml:Theorem lebesgue_measure_iff_LIMSEQ : (* was: lmeasure_iff_LIMSEQ *)
borelScript.sml:Theorem lambda_eq : (* was: lborel_eqI *)
extrealScript.sml:Theorem sup_comm : (* was: SUP_commute *)
extrealScript.sml:Theorem ext_suminf_sup_eq : (* was: suminf_SUP_eq *)
extrealScript.sml:Theorem pow_half_ser : (* was: suminf_half_series_ereal (HVG) *)
measureScript.sml:val SIGMA_FINITE_ALT = store_thm (* was: sigma_finite (HVG) *)
measureScript.sml:val SIGMA_FINITE_ALT2 = store_thm (* was: sigma_finite_measure (HVG) *)
measureScript.sml:Theorem MEASURABLE_IF : (* was: measurable_If *)
measureScript.sml:Theorem MEASURABLE_IF_SET : (* was: measurable_If_set *)
real_borelScript.sml:Theorem borel_eq_gr_less : (* was: borel_eq_greaterThanLessThan *)
real_borelScript.sml:Theorem borel_eq_less : (* was: borel_eq_halfspace_less *)
real_borelScript.sml:Theorem REAL_ARCH_INV : (* was: reals_Archimedean *)
real_borelScript.sml:Theorem borel_eq_le : (* was: borel_eq_halfspace_le *)
real_borelScript.sml:Theorem LINE_MONO : (* was: line_subset *)
real_borelScript.sml:Theorem LINE_MONO_EQ : (* was: line_subset_iff *)
real_borelScript.sml:Theorem BALL_IN_LINE : (* was: ball_subset_line *)
real_borelScript.sml:Theorem REAL_IN_LINE : (* was: mem_big_line *)
real_borelScript.sml:Theorem LINE_MONO_SUC : (* was: line_subset_Suc *)
sigma_algebraScript.sml:Theorem INTER_SPACE_EQ1 : (* was: Int_space_eq1 *)
sigma_algebraScript.sml:Theorem INTER_SPACE_EQ2 : (* was: Int_space_eq2 *)
sigma_algebraScript.sml:Theorem SEMIRING_SETS_COLLECT : (* was: sets_Collect_conj *)
sigma_algebraScript.sml:Theorem RING_FINITE_BIGUNION1 : (* was: finite_Union *)
sigma_algebraScript.sml:Theorem RING_FINITE_BIGUNION2 : (* was: finite_UN *)
sigma_algebraScript.sml:Theorem RING_DIFF_ALT : (* was: Diff *)
sigma_algebraScript.sml:Theorem RING_OF_SETS_IF : (* was: ring_of_setsI *)
sigma_algebraScript.sml:Theorem RING_OF_SETS_IFF : (* was: ring_of_sets_iff *)
sigma_algebraScript.sml:Theorem RING_INSERT : (* was: insert_in_sets *)
sigma_algebraScript.sml:Theorem RING_SETS_COLLECT : (* was: sets_Collect_disj *)
sigma_algebraScript.sml:Theorem RING_SETS_COLLECT_FINITE : (* was: sets_collect_finite_Ex *)
sigma_algebraScript.sml:Theorem algebra_alt : (* was: algebra_alt_eq *)
sigma_algebraScript.sml:Theorem ALGEBRA_COMPL_SETS : (* was: compl_sets *)
sigma_algebraScript.sml:Theorem algebra_alt_union : (* was: algebra_iff_Un *)
sigma_algebraScript.sml:Theorem algebra_alt_inter : (* was: algebra_iff_Int *)
sigma_algebraScript.sml:Theorem ALGEBRA_SETS_COLLECT_NEG : (* was: sets_Collect_neg *)
sigma_algebraScript.sml:Theorem ALGEBRA_SETS_COLLECT_IMP : (* was: sets_Collect_imp *)
sigma_algebraScript.sml:Theorem ALGEBRA_SETS_COLLECT_CONST : (* was: sets_Collect_const *)
sigma_algebraScript.sml:Theorem ALGEBRA_SINGLE_SET : (* was: algebra_single_set *)
sigma_algebraScript.sml:Theorem ALGEBRA_RESTRICT : (* was: restricted_algebra *)
sigma_algebraScript.sml:Theorem BINARY_RANGE : (* was: range_binary_eq *)
sigma_algebraScript.sml:Theorem UNION_BINARY : (* was: Un_range_binary *)
sigma_algebraScript.sml:Theorem INTER_BINARY : (* was: Int_range_binary *)
sigma_algebraScript.sml:Theorem sigma_algebra_alt : (* was: SIGMA_ALGEBRA_ALT_EQ / sigma_algebra_alt_eq *)
sigma_algebraScript.sml:Theorem sigma_algebra_alt_pow : (* was: sigma_algebra_iff2 *)
sigma_algebraScript.sml:val lemma = prove ((* was: countable_Union *)
sigma_algebraScript.sml:Theorem SIGMA_ALGEBRA_COUNTABLE_UN : (* was: countable_UN *)
sigma_algebraScript.sml:Theorem SIGMA_ALGEBRA_COUNTABLE_UN' : (* was: countable_UN' *)
sigma_algebraScript.sml:Theorem SIGMA_ALGEBRA_COUNTABLE_INT : (* was: countable_INT *)
sigma_algebraScript.sml:Theorem SIGMA_ALGEBRA_COUNTABLE_INT' : (* was: countable_INT' *)
sigma_algebraScript.sml:Theorem sigma_sets_BIGUNION : (* was: sigma_sets_union *)
sigma_algebraScript.sml:Theorem sigma_sets_union : (* was: sigma_sets_Un *)
sigma_algebraScript.sml:Theorem sigma_sets_BIGINTER : (* was: sigma_sets_Inter *)
sigma_algebraScript.sml:Theorem sigma_sets_BIGINTER2 : (* was: sigma_sets_INTER *)
sigma_algebraScript.sml:Theorem sigma_sets_fixpoint : (* was: sigma_sets_eq *)
```

**Comment by binghe** [comment]
I added another big theorem `BOREL_INDUCT` (from HVG's work) which can be used to quickly prove extreal-valued Borel measurable funtions:

```
   [BOREL_INDUCT]  Theorem
      
      ⊢ ∀f m P.
            measure_space m ∧
            f ∈ Borel_measurable (m_space m,measurable_sets m) ∧
            (∀x. 0 ≤ f x) ∧
            (∀f g.
                 f ∈ Borel_measurable (m_space m,measurable_sets m) ∧
                 g ∈ Borel_measurable (m_space m,measurable_sets m) ∧
                 (∀x. x ∈ m_space m ⇒ f x = g x) ∧ P f ⇒
                 P g) ∧ (∀A. A ∈ measurable_sets m ⇒ P (𝟙 A)) ∧
            (∀f c.
                 f ∈ Borel_measurable (m_space m,measurable_sets m) ∧
                 0 ≤ c ∧ (∀x. 0 ≤ f x) ∧ P f ⇒
                 P (λx. c * f x)) ∧
            (∀f g.
                 f ∈ Borel_measurable (m_space m,measurable_sets m) ∧
                 g ∈ Borel_measurable (m_space m,measurable_sets m) ∧
                 (∀x. 0 ≤ f x) ∧ P f ∧ (∀x. 0 ≤ g x) ∧ P g ⇒
                 P (λx. f x + g x)) ∧
            (∀u.
                 (∀i. u i ∈ Borel_measurable (m_space m,measurable_sets m)) ∧
                 (∀i x. 0 ≤ u i x) ∧ (∀x. mono_increasing (λi. u i x)) ∧
                 (∀i. P (u i)) ⇒
                 P (λx. sup (IMAGE (λi. u i x) 𝕌(:num)))) ⇒
            P f
```

This theorem is added into `lebesgueTheory` instead of `borelTheory` because it relies on several local lemmas in `lebesgueTheory`.

**Comment by binghe** [comment]
I have completed the porting of Radon-Nikodym Theorem (for sigma-finite measures) from HVG’s legacy code in another branch. I’ll send another PR (with another 5000+ lines of new code) once the present one gets merged.

**Comment by mn200** [comment]
Thanks for all this!

Incidentally, the Axiom of Choice is baked into our HOL axiomatisation from a very early stage: the existence of the Hilbert choice operator is equivalent to it.  Thus things like Zorn's lemma are proved and accessible in the core system (`set_relationTheory` for ZL).

**Comment by binghe** [comment]
> Thanks for all this!
> 
> Incidentally, the Axiom of Choice is baked into our HOL axiomatisation from a very early stage: the existence of the Hilbert choice operator is equivalent to it. Thus things like Zorn's lemma are proved and accessible in the core system (`set_relationTheory` for ZL).

That's great, thanks for the hints!

**Pull request merged**
