### PR TITLE
Fermat

### PR DESCRIPTION
**Pull request by jhlchan**
Provide scripts for Fermat's Two Squares Theorem, as well as Fermat's Little Theorem, with library update merge.

### CODE REVIEW

**Comment by jhlchan** [comment]
Would like to make more changes and commit, then reopen this again.

**Comment by mn200** [comment]
You can extend an open pull request with more commits by just pushing to the relevant branch.  The new commits then just show up here.  See, for example: https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo

**Comment by binghe** [comment]
Great work!

I think, in the future, maybe we can try to move the algebra theories in `example/algebra` to `$HOLDIR/src/algebra` as part of the core theories, as the basis of the `AKS` and `fermat` examples.

File in each subdirectory of `example/algebra` can be merged into just one single theory file, i.e. eventually we just have a few new (big) theories: `fieldTheory`, `finitefieldTheory`, `groupTheory`, `linearTheory`, `monoidTheory`, `polynomialTheory` and `ringTheory`.  On the other hand, the existing theories in `src/ring` folder should be checked to see if they can be merged into the new `algebra` theories, or just marked as obsoleted core theory and moved back to `examples/ring`.

Furthermore, if we move `real_topology`, `integration` and `derivative`, etc. (those ported from HOL-Light) into a new folder `src/analysis` and try to merge all the calculus-related stuff from `src/real`, eventually HOL4 got three big pure mathematics core theory groups: `algebra`, `analysis` and `probability`, each with deep enough yet basic results.

--Chun

**Comment by konrad-slind** [comment]
This is conceptually the right idea. But there is some requirement that the
core theories build reasonably quickly. In the distant past this was approx
20 minutes, not sure what it is now. It could be that the parallelization
feature of Holmake will support quick builds..

Also, there is the requirement that any changes to the core that break
things need to be "feasibly fixable". If the core theories gets too big
then it becomes harder to propagate changes.

Konrad.

**Comment by mn200** [comment]
For what it's worth, the `algebra` example builds in 7 minutes on my elderly (_c._ 2014) Linux desktop.

**Comment by jhlchan** [comment]
So far, only two projects AKS and fermat are using these algebra libraries, by the same author. I think when more people and projects are using it then we can consider if putting algebra to core libraries is beneficial.

**Comment by mn200** [comment]
Thanks for all your work on this!

**Comment by binghe** [comment]
There's a broken proof under `--expk`, in `examples/algebra/polynomial/polyFieldModuloScript.sml`:

```
Proof of 

∀r.
    Field r ⇒
    ∀n.
        n < char r ⇒
        INJ (λs. PPIMAGE (λc. X − |c|) s) (PPOW (natural n))
          (PolyRing r).carrier

failed.
Failed to prove theorem poly_prod_set_image_X_sub_c_inj.
```

**Comment by jhlchan** [comment]
> There's a broken proof under `--expk`, in `examples/algebra/polynomial/polyFieldModuloScript.sml`:
> 
> ```
> Proof of 
> 
> ∀r.
>     Field r ⇒
>     ∀n.
>         n < char r ⇒
>         INJ (λs. PPIMAGE (λc. X − |c|) s) (PPOW (natural n))
>           (PolyRing r).carrier
> 
> failed.
> Failed to prove theorem poly_prod_set_image_X_sub_c_inj.
> ```

Please get the latest version of develop and try a clean compile from Holmakefile. I just did that and polyFieldModuloScript compiled ok.

**Comment by binghe** [comment]
> Please get the latest version of develop and try a clean compile from Holmakefile. I just did that and polyFieldModuloScript compiled ok.

I've made some fixes by myself (#873). Thanks to your good coding style, many proofs are short and clear enough to be maintained, even for people who has no related math backgrounds.

**Comment by jhlchan** [comment]
> > There's a broken proof under `--expk`, in `examples/algebra/polynomial/polyFieldModuloScript.sml`:
> > ```
> > Proof of 
> > 
> > ∀r.
> >     Field r ⇒
> >     ∀n.
> >         n < char r ⇒
> >         INJ (λs. PPIMAGE (λc. X − |c|) s) (PPOW (natural n))
> >           (PolyRing r).carrier
> > 
> > failed.
> > Failed to prove theorem poly_prod_set_image_X_sub_c_inj.
> > ```
> 
> Please get the latest version of develop and try a clean compile from Holmakefile. I just did that and polyFieldModuloScript compiled ok.

Thanks for the corrections in [https://github.com/HOL-Theorem-Prover/HOL/pull/873](#873) The latest HOL4 update works fine now.

**Pull request merged**
