### PR TITLE
Cumulative fixes for HOL4 building in Moscow ML

### PR DESCRIPTION
**Pull request by binghe**
Hi, this trivial patch fixes all issues raised when building latest HOL4 in Moscow ML.

### CODE REVIEW

**Comment by mn200** [comment]
I think my recent changes mean that the patches to do with the `Theorem` “keyword” aren't required anymore. I think it is just the dependency information in `src/metis` that needs fixing.

**Comment by binghe** [comment]
What recent changes? I was building on 8649983c4924097c8a62e531247200c9bf24067c (the latest commit on `master` at this moment), and without those changes related to `Theorem` the mosml build was still broken...

**Comment by mn200** [comment]
Changes I am seconds away from pushing ...

**Comment by binghe** [comment]
Very good, then this PR is not needed any more.

**Comment by binghe** [comment]
Sorry, I didn't realized that you still need the changes in `src/metis/Holmakefile` (because I just found the mosml build after your these changes is still broken at that part), but I guess you can make the changes by yourself.

**Pull request closed without merging**
