### PR TITLE
Minkowski's inequality and its applications in Probability

### PR DESCRIPTION
**Pull request by binghe**
Hi,

In this PR, Minkowski's inequality (for Lebesgue integration), also called _triangle inequality of (semi)norm_, has been formalized. It is essentially another corollary of Hölder's Inequality (#972).
```
[Minkowski_inequality]  Theorem (martingaleTheory)
      ⊢ ∀p m u v.
          measure_space m ∧ 1 ≤ p ∧ p ≠ +∞ ∧ u ∈ function_space p m ∧
          v ∈ function_space p m ⇒
          (λx. u x + v x) ∈ function_space p m ∧
          seminorm p m (λx. u x + v x) ≤ seminorm p m u + seminorm p m v
```

What I really need (in proving other more advanced probability theorems, still in progress) is the case when `p = 2` and the first part of the conclusions, that if two (or more) random variables each have finite second moments (i.e. finite variance), so is their summation:
```
[finite_second_moments_add]  Theorem (probabilityTheory)
      ⊢ ∀p X Y.
          prob_space p ∧ real_random_variable X p ∧
          real_random_variable Y p ∧ finite_second_moments p X ∧
          finite_second_moments p Y ⇒
          finite_second_moments p (λx. X x + Y x)

[finite_second_moments_sum]  Theorem (probabilityTheory)
      ⊢ ∀p X J.
          prob_space p ∧ FINITE J ∧
          (∀i. i ∈ J ⇒ real_random_variable (X i) p) ∧
          (∀i. i ∈ J ⇒ finite_second_moments p (X i)) ⇒
          finite_second_moments p (λx. ∑ (λn. X n x) J)
```

Note that, the previous added `norm` in #972 has now been _renamed_ to `seminorm`:
```
[seminorm_def]  Definition      
      ⊢ ∀p m f.
          seminorm p m f =
          if p = +∞ then
            inf {c | 0 < c ∧ measure m {x | x ∈ m_space m ∧ c ≤ abs (f x)} = 0}
          else ∫⁺ m (λx. abs (f x) powr p) powr p⁻¹
```

This is because, according to [1, p.119], the definiteness of a norm is not fulfilled since a zero "norm" (of the present definition) only implies the function is almost everywhere zero, as the following lemma shows:
```
[seminorm_eq_0]  Theorem      
      ⊢ ∀p m f.
          measure_space m ∧ 1 ≤ p ∧ p ≠ +∞ ∧
          f ∈ Borel_measurable (m_space m,measurable_sets m) ⇒
          (seminorm p m f = 0 ⇔ AE x::m. f x = 0)
```

The previously added Hölder's Inequality and Cauchy-Schwarz Inequality have been extended to include the integrability conclusions, e.g. the part `integrable m (λx. u x * v x)` in `Hoelder_inequality` is new:
```
[Hoelder_inequality]  Theorem      
      ⊢ ∀m u v p q.
          measure_space m ∧ 0 < p ∧ 0 < q ∧ p⁻¹ + q⁻¹ = 1 ∧ p ≠ +∞ ∧
          q ≠ +∞ ∧ u ∈ function_space p m ∧ v ∈ function_space q m ⇒
          integrable m (λx. u x * v x) ∧
          ∫ m (λx. abs (u x * v x)) ≤ seminorm p m u * seminorm q m v
```

To support the above results, some new extreal lemmas are added. A few existing theorems are enhanced with weaker antecedents. Minor incompatibilities, but I think most of them were added after the last official release.

P. S. It's not clear if the present PR may have any conflict with the existing PR #1006. If  #1006 were merged first, I will resolve any potential conflicts here by merging from latest `develop` then.

## Other changes

In `borelTheory`, due to historical reasons, the Lebesgue measure space (`lebesgue`) defined by HVG Concordia people has been obsoleted by my `lborel` (Construction of one-dimensional household Borel measure space by Carathédory's Extension Theorem).  These `lebesgue` stuff are not needed in later developments of Probability Theory, instead, the study of Lebesgue measure space as a completion of Borel measure space is of independent interest. Now I moved them into a separated theory file `lebesgue_measureTheory` under `examples/probability`. (This allows me to remove dependencies of legacy tactics (of `jrhUtils` et al.) from core probability scripts.)     I plan to prove more results (Lebesgue measure space as a completion of Borel measure space) in the future, to further charge this new theory file in examples.

Chun Tian

[1] Schilling, R.L.: Measures, Integrals and Martingales (Second Edition). Cambridge University Press (2017).

### CODE REVIEW

**Comment by mn200** [comment]
Thanks for this!  A very minor thing: if you have time and knowledge of how to fiddle this sort of thing in `git`, I'd appreciate a slight tweak whereby the change to `hurdUtils` gets pushed into a separate commit that describes what's happening there.  (I'm thinking of someone browsing the output of `git log src/res_quan` and getting a description of changes in `src/probability` that have nothing to do with what happened to `hurdUtils`.)

**Comment by binghe** [comment]
> Thanks for this! A very minor thing: if you have time and knowledge of how to fiddle this sort of thing in `git`, I'd appreciate a slight tweak whereby the change to `hurdUtils` gets pushed into a separate commit that describes what's happening there. (I'm thinking of someone browsing the output of `git log src/res_quan` and getting a description of changes in `src/probability` that have nothing to do with what happened to `hurdUtils`.)

OK, I have reverted the changes in `hurdUtils.sml`. By squashing all 3 commits into a single one during the merging, the final git log won't show any changes in `src/res_quan`, I believe.  (The reverted changes can be part of future PRs, in separate commit with dedicated logs, as I think it's still useful, but doesn't deserve an dedicate PR.)

**Comment by mn200** [comment]
Thanks!  I'll do a squash-merge as you suggest.

**Comment by binghe** [comment]
> Thanks! I'll do a squash-merge as you suggest.

Thanks.

**Pull request merged**
