### PR TITLE
Register Machine in HOL4

### PR DESCRIPTION
**Pull request by zozozoeyc**
Added register machine model, tools, sample machines, partial proof for register machine to recursive functions, partial proofs for register machine simulating pair functions, and some tests.

### CODE REVIEW

**Comment by mn200** [comment]
You need to fix the failures flagged in the CI test above. In particular

    tools/unicode-grep/unicode-grep examples

is finding problems with trailing whitespace in your files.

**Comment by mn200** [comment]
Thanks!

**Comment by zozozoeyc** [comment]
Thank you~ :D

**Comment by binghe** [comment]
This example cannot build: (I'm using `--expk`, didn't try `--stdknl`)

```
Saved definition __ "correct1_rmcorr_def"
Saved definition __ "correct2_def"
Saved theorem _____ "rmcorr_seq"
Proof of 

(∀rs. Q rs ⇒ Q' rs) ∧ rmcorr m q1 P (SOME q2) Q ∧ rmcorr m q2 Q' q3 R ⇒
rmcorr m q1 P q3 R

failed.
First unsolved sub-goal is

rs' = rs''

Failed to prove theorem rmcorr_seq_V.

Exception raised at Tactical.TAC_PROOF:
unsolved goals
error in quse /Users/binghe/ML/HOL/examples/computability/register/rmToolsScript.sml : HOL_ERR {message = "unsolved goals", origin_function = "TAC_PROOF", origin_structure = "Tactical"}
error in load /Users/binghe/ML/HOL/examples/computability/register/rmToolsScript : HOL_ERR {message = "unsolved goals", origin_function = "TAC_PROOF", origin_structure = "Tactical"}
```

The previous `Holmakefile` in `examples/computability/register` was deleted, but `examples/computability/register/rmModelScript.sml` depends on `primrecfnsTheory` in upper directory. To resolve the dependency issue, I have to add `examples/computability/register/Holmakefile` with the following contents:

```
INCLUDES = ..
```

Then I saw the above build error.  The regression/CI tests passed because this example wasn't in any build sequence in `tools/sequences`, thus the newly added code were not tested during the CI tests.

--Chun

**Comment by mn200** [comment]
I'm aware of these failures because my local regression infrastructure checks everything at test-level 3.  (Travis doesn't because such testing takes longer than they're willing to give us.)  

See the archive of these results at [Sourceforge](https://sourceforge.net/p/hol/mailman/hol-builds/?viewmonth=202003&style=flat).

**Pull request merged**
