### PR TITLE
Add functions to search for constants of a given type to bossLib

### PR DESCRIPTION
**Pull request by HeikoBecker**
This pull request adds two new functions (`find_consts` and `find_consts_thy`) to `bossLib`, documentation in `help/doc` for the new functions, and a keybinding for the emacs mode (`M-h C-c`) to call `find_consts`

### CODE REVIEW

**Comment by mn200** [comment]
Can you use `M-h c` for this in the emacs mode please?  This then displaces the `check-current-theory` entry-point, which I'd be happy to see on `M-h C`. 

The control prefix under `M-h` is (mostly?) used for toggling various trace variables, and I'd like to keep that convention if possible.

**Comment by mn200** [comment]
Oh, and target the `develop` branch with the PR please.

**Comment by HeikoBecker** [comment]
I changed the request to target the develop branch. But somehow I created 2 new merge commits. Please feel free to squash them.

**Comment by mn200** [comment]
Thanks!

**Pull request merged**
