### PR TITLE
Added Bisimulation to relationTheory

### PR DESCRIPTION
**Pull request by JamesShaker**
Just added a simple generic definition of what makes a relation a bisimulation and also the notion of bisimulation relation (which says two states are related if a bisimulation exists between them). Proved the bisimulation relation is an equivalence.

### CODE REVIEW

**Comment by mn200** [comment]
Can you make the PR merge into the `develop` branch please?

**Comment by JamesShaker** [comment]
Sure thing

**Comment by mn200** [comment]
Thanks!

**Comment by binghe** [comment]
This is a very inspiring work, thanks. I'm modifying my CCS example, defining my bisimulation of CCS upon this general definition:

```
   [STRONG_BISIM_def]  Definition
      
      ⊢ ∀R. STRONG_BISIM R ⇔ BISIM TRANS R

   [STRONG_EQUIV_IS_BISIM_REL]  Theorem
      
      ⊢ STRONG_EQUIV = BISIM_REL TRANS
```

**Pull request merged**
