### PR TITLE
Use _Theory.dat for loading theory data into _Theory.sml

### PR DESCRIPTION
**Pull request by barakeel**

### CODE REVIEW

**Comment by xrchz** [comment]
Note, there is some `loadPath` hackery in `load_thydata` in `TheoryReader.sml` - if there's a better way to do this that works, it would be good to know. @mn200 maybe you have an idea?

**Comment by barakeel** [comment]
Somehow, the cakeml build failed because of the loadPath hackery.

**Comment by binghe** [comment]
I think after this work the `--otknl` build on `master` has been broken...

**Comment by mn200** [comment]
I certainly agree that `--otknl` is broken; fixing it is on my todo list.

**Pull request merged**
