### PR TITLE
Fix bug in Lassie's Holmakefile preventing clean rebuilds

### PR DESCRIPTION
**Pull request by HeikoBecker**

### CODE REVIEW

**Comment by mn200** [comment]
To get this tested on my local machine, you need to also adjust a sequence file under `tools/sequences`.

**Comment by mn200** [comment]
I really don't like having to re-download code from Stanford and to then recompile it even if nothing has changed.  Is there no way around this?

**Comment by HeikoBecker** [comment]
The bugs introduced by #877 should be fixed now. I still need to adapt `tools/sequences` and change the Holmakefiles. But at least there is a build now that passes CI.

**Comment by mn200** [comment]
I take it you see the problems on Travis:
```
 /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- execrunner (LoadError)
8321 	from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
8322 	from interactive/run:9:in `<main>'
8323 error in quse /home/travis/build/HOL-Theorem-Prover/HOL/examples/lassie/src/LassieLib.sml : Fail "Run script returned no arguments"
8324 error in load $(HOLDIR)/examples/lassie/src/LassieLib : Fail "Run script returned no arguments"
8325 error in load /home/travis/build/HOL-Theorem-Prover/HOL/examples/lassie/src/LassieTestScript : Fail "Run script returned no arguments"
8326 Uncaught exception: Fail "Run script returned no arguments"
```

**Comment by HeikoBecker** [comment]
> I take it you see the problems on Travis:
> 
> ```
>  /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- execrunner (LoadError)
> 8321 	from /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 8322 	from interactive/run:9:in `<main>'
> 8323 error in quse /home/travis/build/HOL-Theorem-Prover/HOL/examples/lassie/src/LassieLib.sml : Fail "Run script returned no arguments"
> 8324 error in load $(HOLDIR)/examples/lassie/src/LassieLib : Fail "Run script returned no arguments"
> 8325 error in load /home/travis/build/HOL-Theorem-Prover/HOL/examples/lassie/src/LassieTestScript : Fail "Run script returned no arguments"
> 8326 Uncaught exception: Fail "Run script returned no arguments"
> ```

Yes, I think I messed up the Holmakefile ordering again... Looking into it.

**Comment by HeikoBecker** [comment]
The latest commit should fix all of the remaining bugs, as well as make sure that dependencies are downloaded only once, or after reinitializing.

**Comment by mn200** [comment]
Why do you have `-j1` turned on?  It seems as if the examples (at least) could be done  in parallel.

**Comment by mn200** [comment]
Hmm.  I spoke too soon.  When I tried with `Holmake -j4`, I got what looked like bad (looping?) behaviour.  Is there some shared resource that can only be accessed sequentially?

**Comment by mn200** [comment]
Thanks for your work getting this to pass the various tests!

**Comment by HeikoBecker** [comment]
> Why do you have `-j1` turned on? It seems as if the examples (at least) could be done in parallel.

In theory, yes. But somehow SEMPRE does not like having multiple versions running in parallel, thus we need to limit the processes with the `-j1`. Unfortunately there is nothinh I can do about this.

**Pull request merged**
