### PR TITLE
Matrices in Euclidean space, and elementary linear algebra

### PR DESCRIPTION
**Pull request by binghe**
Hi,

this PR continues #1037 and ported the remaining theorems of HOL-Light's `vectors.ml` from old code in PR #513.  I made a separation between vector- and matrix-related theorems and now put all matrix theorems into a new `matrixTheory` in addition of the existing `vectorTheory`, in case the potential users may find the name "vector" misleading when they were looking for formalization of matrix.

For example, beside other basic matrix operations, the inversion of matrix is defined in this way:
```
MATRIX_INV_DEF
⊢ ∀A. MATRIX_INV A = @A'. A ** A' = 1m ∧ A' ** A = 1m
```
Not every matrix is invertible. Those invertible must satisfy the following predicate:
```
invertible_def
⊢ ∀A. invertible A ⇔ ∃A'. A ** A' = 1m ∧ A' ** A = 1m
```
Then there's a theorem saying that, for each invertible matrix, applying inversion operation twice you get the original matrix:
```
MATRIX_INV_INV
⊢ ∀A B. invertible A ⇒ MATRIX_INV (MATRIX_INV A) = A
```

(It would be nice to have an actual algorithm as a conversion for calculating matrix inversions, returning a theorem `|- MATRIX_INV A = ...` for any concrete invertible matrix A given as input.)

In `pred_setTheory`, beside minor cleanups, I added several theorems for HOL-Light compatibility. In this way many original HOL-Light proofs of matrix theorems basically need only grammar changes: the same tactics just work for HOL4 (also thanks to many previously compatibility fixes, including the new `REAL_ARITH_TAC`, well, mostly done by myself).

It remains to port the theory of determinants (a special application of `matrixTheory` to NxN square matrices).

Chun Tian

### CODE REVIEW

**Comment by binghe** [comment]
I must say, that this whole matrix formalization (even the original work in HOL Light) is far from satisfaction, because "Linear algebra works over any field." [1], but currently this HOL theory is specified to real numbers.   If the field is rational numbers (the half-broken `ratTheory`, e.g.) or rational functions, in theory many existing proofs should still work.  One solution is link with `example/algebra` and parameterize all theorems and then specialize a version for reals. Another (better) solution is (perhaps) to define the `vectorTheory` and `matrixTheory` as ML functors and instantiate the specific theories for linear algebra over different fields (like the floating numbers of different bits).  The `REAL_ARITH_TAC` has similar possible extensions, as it's implicitly used in some vector and matrix proofs.

[1] D. Cox, J. Little, D. O'Shea, Ideals, Varieties, and Algorithms, Third Edition,
      Springer Science & Business Media, 2013. doi:10.1007/978-1-4757-2693-0.

**Comment by binghe** [comment]
The last commit is a fix for the remaining compilation issues caused by #1067 on `develop` under Moscow ML.

**Comment by binghe** [comment]
The last commits added something in the next release notes for the present vector and matrix theories, and also for the new `REAL_ARITH` (#1043).

**Comment by mn200** [comment]
I agree that a nice algebraic presentation of this would be nice.  I'm not sure that the functor-based approach is particularly good.  We did use to do our theory of _n_-bit words that way, and it was rather awkward.  Note that though there is a functor in `src/floating-point` it is only used to generate `..Syntax` structures, not the actual theories, which all just build on the existing words development and are polymorphic over word sizes that way.

**Comment by mn200** [comment]
Anyway, thanks for getting all this done!

**Pull request merged**
