### PR TITLE
Lemmas about r.v.'s having identical distribution

### PR DESCRIPTION
**Pull request by binghe**
Hi,

this PR continues the formalization of probability theory, in particular, some basic properties of r.v.'s (random variables) having identical distribution, which is naturally defined below:

```
   [identical_distribution_def]  Definition      
      ⊢ ∀p X E J.
            identical_distribution p X E J ⇔
            ∀i j s.
                s ∈ subsets E ∧ i ∈ J ∧ i ∈ J ⇒
                distribution p (X i) s = distribution p (X j) s
```

A (countable) sequence of r.v.'s having identical distribution(s), no matter if they were independent or not, must have exactly the same mathematical expectation. In particular, if one of them is integrable (i.e. finite expectation), so are all others:

```
   [identical_distribution_expectation]  Theorem      
      ⊢ ∀p X.
            prob_space p ∧ (∀n. random_variable (X n) p Borel) ∧
            identical_distribution p X Borel 𝕌(:num) ⇒
            ∀n. expectation p (X n) = expectation p (X 0)
   
   [identical_distribution_integrable]  Theorem      
      ⊢ ∀p X.
            prob_space p ∧ (∀n. random_variable (X n) p Borel) ∧
            identical_distribution p X Borel 𝕌(:num) ∧ integrable p (X 0) ⇒
            ∀n. integrable p (X n)
```

The underlying reason (identical distributed r.v.'s have the same expectation) is that their expectation all equals to the integration of the same function `\x. x` of the same probability space induced from their (shared) distribution function:

```
   [expectation_distribution]  Theorem      
      ⊢ ∀p X f.
            prob_space p ∧ random_variable X p Borel ∧
            f ∈ Borel_measurable Borel ⇒
            expectation p (f ∘ X) =
            ∫ (space Borel,subsets Borel,distribution p X) f ∧
            (integrable p (f ∘ X) ⇔
             integrable (space Borel,subsets Borel,distribution p X) f)
```

The above result comes from a deep "transformation" theorem [1, p. 154] (Chapter 15, Integrals with Respect to Image Measures) of Lebesgue Integrals, which was missing but now is formalized (which I put in `martingaleTheory`, as `lebesgueTheory` is too big to put new big theorems):

```
   [integral_distr]  Theorem      
      ⊢ ∀M B f u.
            measure_space M ∧ sigma_algebra B ∧
            f ∈ measurable (m_space M,measurable_sets M) B ∧
            u ∈ Borel_measurable B ⇒
            ∫ (space B,subsets B,distr M f) u = ∫ M (u ∘ f) ∧
            (integrable (space B,subsets B,distr M f) u ⇔
             integrable M (u ∘ f))
```

Almost all other newly added theorems in this PR serve for the above mentioned ones. With these additions, now it's possible to express "The Law of Large Numbers" (LLN) for I.I.D. r.v.'s (independent with identical distributions). The following deep estimation theorem of expectations will be essential in proving LLN, the weak one:

```
   [expectation_bounds]  Theorem      
      ⊢ ∀p X.
            prob_space p ∧ real_random_variable X p ⇒
            suminf (λn. prob p {x | x ∈ p_space p ∧ &SUC n ≤ abs (X x)}) ≤
            expectation p (abs ∘ X) ∧
            expectation p (abs ∘ X) ≤
            1 +
            suminf (λn. prob p {x | x ∈ p_space p ∧ &SUC n ≤ abs (X x)})
```

Regards,

Chun Tian

[1] Schilling, R.L.: Measures, Integrals and Martingales (2nd Edition). Cambridge University Press (2017).

### CODE REVIEW

**Comment by binghe** [comment]
CI doesn't work any more? Anyway I don't think anything is broken here with latest changes in `develop`...

**Comment by mn200** [comment]
Yeah, I don't know what Travis is / isn't doing.

**Comment by binghe** [comment]
I'm about to submit next PR (Fubini's theorem) once the present one were accepted/merged ...

**Comment by mn200** [comment]
Thanks for your work on this!

**Pull request merged**
