### PR TITLE
Length nil

### LINKED ISSUE #346: Add `LENGTH x = 0 <=> x = []` to automatic rewrites
Not only that way round, but also with `0 = LENGTH x` as the lhs. 
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34547415-add-length-x-0-x-to-automatic-rewrites?utm_campaign=plugin&utm_content=tracker%2F495335&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F495335&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by xrchz**
Closes #346

### CODE REVIEW

**Comment by xrchz** [comment]
What's the difference between the push and pr travis checks? Which one matters for getting this merged?

**Comment by mn200** [comment]
No idea. I didn't think they were different.  It could be that one failed for transient reasons.  I'm happy for you to merge if you can get a `build -t3` to go through on a machine of your own.

**Comment by xrchz** [comment]
I've got it to go through up till `!!examples/ARM_security_properties` - it's really hard to test because of random exit code failures. Apparently the Travis checks are OK now (it doesn't do level 3?)

**Comment by mn200** [comment]
The level 3 tests take far too long to run on Travis.  I can try it on my mac, which only fails "randomly" very occasionally.

**Pull request merged**
