### PR TITLE
Further extensions to the CCS example (thesis work of Chun Tian)

### PR DESCRIPTION
**Pull request by binghe**
Hi,

This PR contains the third part of my CCS project, which is actually my MSc thesis work, titled as **A Formalization of Unique Solutions of Equations in Process Algebra**.

In the additional ~7000 lines of proof scripts, I mainly formalized the 3 so-called "Unique Solutions of Equations" theorems presented in the book of Robin Milner [1], plus a further development [2] by my thesis advisor, Prof. Davide Sangiorgi (he was a student of Milner), based on "expansion" and "contraction" relations.   I also developed rather complete theories of "Bisimulation Upto", "Trace" and "Congruence" for CCS.

I hope my work can be merged to HOL official first, then in my thesis paper (to be presented in December 20, this year) I can refer to HOL repository as the official place of my proof scripts.

I've tested building with HOL stdknl and expk, plus HOL building with Moscow ML (expk only).  Tailing spaces were removed according to the changes by HOL maintainers.

Regards,

Chun Tian
University of Bologna

[1] Milner, R.: Communication and concurrency. (1989).
[2] Sangiorgi, D.: Equations, contractions, and unique solutions. ACM SIGPLAN Notices. (2015).

### CODE REVIEW

**Comment by xrchz** [comment]
@mn200 I notice this isn't actually tested by travis - do you have anything else running selftest level 1?

**Comment by mn200** [comment]
The regression tests I run under `cron` (results posted to `hol-builds`) do selftest level 1.

**Comment by xrchz** [comment]
It doesn't look like they get run on pull requests from forks though, right?

**Comment by mn200** [comment]
True.

**Comment by xrchz** [comment]
I'd be happy for this to be merged anyway, if you are.

**Comment by binghe** [comment]
Thanks!

**Pull request merged**
