### PR TITLE
Add reswites and the corresponding ssfrags to “res_quan”

### PR DESCRIPTION
**Pull request by marioxcc**

### CODE REVIEW

**Comment by marioxcc** [comment]
The Travis build fails because of non-ASCII characters in the _comments_. I removed all the Unicode symbols in the proofs, but I see no reason to remove the ones in the comments. Moreover, the non-ASCII characters are those of my first surname (“Castelán”); there is no way to spell my full name within ASCII.

```
mario@svetlana [0] [/home/mario/pex/hol4/HOL_dev/src/res_quan/src]
$ $P/unicode-grep .
./res_quanTools.sml:6:UPDATED                  DATE: 20 Oct 17     BY: Mario Castelán Castro
./res_quanTools.sml:9:"COPYRIGHT" in the HOL4 distribution (note added by Mario Castelán Castro).
./res_quanTools.sml:11:For the avoidance of legal uncertainty, I (Mario Castelán Castro) hereby
./res_quanTools.sig:8:UPDATED       : Mario Castelán Castro, 2017
./res_quanTools.sig:11:"COPYRIGHT" in the HOL4 distribution (note added by Mario Castelán Castro).
./res_quanTools.sig:13:For the avoidance of legal uncertainty, I (Mario Castelán Castro) hereby
./res_quanScript.sml:4:"COPYRIGHT" in the HOL4 distribution (note added by Mario Castelán Castro).
./res_quanScript.sml:6:For the avoidance of legal uncertainty, I (Mario Castelán Castro) hereby
./res_quanScript.sml:17:CHANGED BY: Mario Castelán Castro, 2017
```

**Comment by mn200** [comment]
The trick here is to put the "magic" string `UOK` somewhere on the same line as the Unicode characters.

**Comment by mn200** [comment]
Thanks for your work on this!

**Comment by marioxcc** [comment]
Thanks you. If there is any error with my changes please bring it to my attention and I will try to fix it.

**Pull request merged**
