### PR TITLE
Add higher-order case splits

### PR DESCRIPTION
**Pull request by talsewell**
The higher-order elim rule combines the case_elim and case_rand
theorems already available from Prim_rec. The implication form
uses negation to flip the quantifiers, from a disjunction of
existentially-quantified possibilities to a conjunction of
universally-qualified implications.

### CODE REVIEW

**Comment by mn200** [comment]
Rather than `GEN` and `ISPEC` in the first one, I'd just use `INST_TYPE` to make the range type of the "predicate" variable be `:bool`.    And then, use `REWR_CONV` in the right position (`RAND_CONV`) rather than `REWRITE_RULE` to use the `elim` theorem.  I can do this myself if you don't get around to it in the near future.

**Comment by talsewell** [comment]
Hmm, you're right, that would be simpler.

I fiddled with trying to simplify the conversion in the second one also. It's possible to apply not-exists rule without higher-order mechanisms by first eta-contracting it, but this has to be alternated with beta expansion, so I'm not sure there are any wins there.

**Comment by mn200** [comment]
Given conversation in Slack @ cakeml, I'll leave this a bit longer to give you a chance to make TypeBase changes as well.

**Comment by mn200** [comment]
To be consistent with other names in `TypeBase`, the new entry points could perhaps pick up names ending in `_of`.

**Comment by mn200** [comment]
Awesome; thanks!

**Pull request merged**
