### PR TITLE
Example based on Dr. Eric Hehner's predicative theory of programming …

### PR DESCRIPTION
**Pull request by vo1stv**
…and master thesis by Stephen Motty under supervision of Theodore S. Norvell, Memorial University of Newfoundland.

This example currently defines concepts for proving correctness of imperative programs, specifically:
1) definition of sequential composition
2) proof of forward substitution law

### CODE REVIEW

**Comment by xrchz** [comment]
It would be good to add the new `examples/imperative` directory to the automatically tested build sequence somewhere, which can be found in `tools/sequences` - perhaps under `more-theories`. @mn200 might have an opinion about where.

**Comment by mn200** [comment]
Yes, please add to `tools/sequences/more-theories`.

**Comment by vo1stv** [comment]
Thanks.  I'm currently testing this, and as suggested by  @mn200 will add the line !example/imperative somewhere inside moretheories.
Early results show that it does not like seeing swapping.sml in the directory.  I plan to move swapping.sml to the parent examples directory (alongside euclid.sml and fol.sml) unless you suggest another solution.  The file swapping.sml is meant to be run interactively (i.e. ' use "swapping.sml";' )

**Comment by vo1stv** [comment]
Letting Travis test the changes.

Two things still on my wish-list:
1) How to store Tactics into the Theory.  The current implementation defines the same tactic in two files until I find an example showing how to do this.
2) How to test for an expected failure of a proof

**Comment by mn200** [comment]
You can't really store tactics in a theory. You should define them in a separate library (typically called `fooLib.sml`), and then users of your theory load the `Lib` file.

**Comment by mn200** [comment]
Travis is usually tested with custom sequences (we are not able to have build times go beyond about 40mins), which are specified in the files under `developers/travis/`.

**Comment by mn200** [comment]
I've added a `Holmakefile` to the directory so that the `selftest.exe` file gets built.  I notice that the output currently looks like:

```
: 14:26 [747] ; ./selftest.exe 
OK
Proof of 

(\(s :'a -> num) (s' :'a -> num).
   (s' (x :'a) = (1 :num)) /\ (s' (y :'a) = (2 :num))) [=.
sc (assign y (\(s :'a -> num). (1 :num)))
  (assign x (\(s :'a -> num). s y))

failed.
OK
OK
OK
```

Although the exit code suggests this is OK, I wonder if this is what you expected.

Incidentally, if you could write a `README` for that directory, that would also be awesome.

**Comment by vo1stv** [comment]
Everything looks good to go, except I'm still not sure which Travis configuration is passing the --selftest flag to the build.  I've tested it by  staging changes in a separate branch (i.e. travis), with the following successful result:
```
Building directory examples/imperative [07 Apr, 04:38:37]
ptopTheory                                                                   OK
imperativeTheory                                                             OK
Self-test directory /home/travis/build/vo1stv/HOL/examples/imperative built successfully.

```

**Comment by mn200** [comment]
Travis is currently testing it with `examples/imperative` included: [this build](https://travis-ci.org/HOL-Theorem-Prover/HOL/builds/219548560) in 5 and 6 will test your directory.

**Pull request merged**
