### PR TITLE
Add project work on iTrees (monads, exists/every, finite, paths)

### PR DESCRIPTION
**Pull request by clairexhuang**

### CODE REVIEW

**Comment by clairexhuang** [comment]
Hey, just creating a PR to merge some definitions & theorems for iTrees, including:
- iflat
- imap
- iexists
- ievery
- ifinite

**Comment by binghe** [comment]
Just a remind: please fix Unicode violations first.

**Comment by mn200** [comment]
If you follow the "details" links above you will see how your commit still has Unicode characters and trailing whitespace on some lines.  Please replace the former with ASCII equivalents and delete the latter.  -- Many thanks!

**Comment by binghe** [comment]
Additional note: by adding `-t` when building HOL, the Unicode violations will be checked (and seen locally) at very early stage.

**Comment by mn200** [comment]
Thank you for your work on this!

**Pull request merged**
