### PR TITLE
Add Lassie from CPP 21 paper to examples directory

### PR DESCRIPTION
**Pull request by HeikoBecker**
This adds the code for the CPP'21 paper "Lassie:HOL4 tactics by example" to the HOL4 distribution in the examples directory, and integrates it with the regression tests.

### CODE REVIEW

**Comment by mn200** [comment]
I get a build failure:
```
telemachus:/home/michaeln/HOL/examples/lassie/src                     [develop]
: 19:07 [337] ; Holmake
cd ../sempre &&         git clean -xfd && 	./pull-dependencies core interactive && 	ant core interactive && 	cd ../src
===== Downloading core: Core utilities (need to compile)
Cloning into 'fig'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1533 (delta 0), reused 1 (delta 0), pack-reused 1529
Receiving objects: 100% (1533/1533), 718.54 KiB | 528.00 KiB/s, done.
Resolving deltas: 100% (653/653), done.
make: Entering directory `/home/michaeln/HOL/examples/lassie/sempre/fig'
mkdir -p classes
ant compile
Buildfile: /home/michaeln/HOL/examples/lassie/sempre/fig/build.xml

compile:
    [javac] /home/michaeln/HOL/examples/lassie/sempre/fig/build.xml:4: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 220 source files to /home/michaeln/HOL/examples/lassie/sempre/fig/classes
    [javac] /home/michaeln/HOL/examples/lassie/sempre/fig/src/main/java/fig/basic/OptionsParser.java:507: illegal start of type
    [javac]     List<Field> fields =  new ArrayList<>();
    [javac]                                         ^
    [javac] 1 error

BUILD FAILED
/home/michaeln/HOL/examples/lassie/sempre/fig/build.xml:4: Compile failed; see the compiler error output for details.

Total time: 1 second
make: *** [classes] Error 1
make: Leaving directory `/home/michaeln/HOL/examples/lassie/sempre/fig'
```

**Comment by mn200** [comment]
Is this down to a very old version of java?

**Comment by HeikoBecker** [comment]
I am not sure about this one. I have not experienced the error before. It could be due to the Java version.
Which version of Java are you using?

**Comment by AndreasLoow** [comment]
IIRC the diamond thing was introduced in Java 1.7 -- i.e. more than 10 years ago. Using a more recent Java version should fix this specific problem.

**Comment by mn200** [comment]
```
java version "1.6.0_41"
OpenJDK Runtime Environment (IcedTea6 1.13.13) (6b41-1.13.13-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)
```

How best to update on a Ubuntu 14.04 machine?

**Comment by HeikoBecker** [comment]
According to some StackOverflow sources, OpenJDK 8 should be available (and do the job for now). So the following should work:
``` apt-get install openjdk-8-jdk```
Source: https://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts

**Comment by mn200** [comment]
I found another link that suggested: 
```
sudo apt-get install default-jdk
```
But on trying this, I got:
```
Buildfile: /home/michaeln/HOL/examples/lassie/sempre/build.xml

init:
     [exec] Wrote modules with 324 files to module-classes.txt: cache core corenlp cprune freebase geo880 interactive overnight tables
    [mkdir] Created dir: /home/michaeln/HOL/examples/lassie/sempre/classes
    [mkdir] Created dir: /home/michaeln/HOL/examples/lassie/sempre/libsempre

core:
     [echo] Compiling semparse: core
    [javac] Compiling 134 source files to /home/michaeln/HOL/examples/lassie/sempre/classes
    [javac] javac: invalid target release: 1.8
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

```

**Comment by mn200** [comment]
The other command gives:
```
E: Unable to locate package oracle-java8-set-default
```

I should just upgrade to a more recent Ubuntu.

**Comment by HeikoBecker** [comment]
That looks strange. I will check this offline and report back as soon as I have more information available. 
Just for reference, I just learned that my initial answer was wrong, openJDK 8 is not available in 14.04.

**Comment by binghe** [comment]
Just an irrelevant comment: the build script calls `git clean -xfd` to cleanup something, but this assumes HOL repository is checking out from a Git repository. In a HOL directory extracted from release tarball, this git command may bring some extra issues...

**Comment by binghe** [comment]
> ```
> java version "1.6.0_41"
> OpenJDK Runtime Environment (IcedTea6 1.13.13) (6b41-1.13.13-0ubuntu0.14.04.1)
> OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)
> ```
> 
> 
> How best to update on a Ubuntu 14.04 machine?

You can also manually download Oracle JDK 8u202 [1] (the last JDK 8 release with free license) and extract it into a JDK folder in your Ubuntu 14.04 (I tried, it worked on this Linux), and set up PATH and JAVA_HOME. Then you should have a fully functional Java environment for the Java code here.

[1] https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html

**Comment by HeikoBecker** [comment]
> Just an irrelevant comment: the build script calls `git clean -xfd` to cleanup something, but this assumes HOL repository is checking out from a Git repository. In a HOL directory extracted from release tarball, this git command may bring some extra issues...

> 
> ```
> Buildfile: /home/michaeln/HOL/examples/lassie/sempre/build.xml
> 
> init:
>      [exec] Wrote modules with 324 files to module-classes.txt: cache core corenlp cprune freebase geo880 interactive overnight tables
>     [mkdir] Created dir: /home/michaeln/HOL/examples/lassie/sempre/classes
>     [mkdir] Created dir: /home/michaeln/HOL/examples/lassie/sempre/libsempre
> 
> core:
>      [echo] Compiling semparse: core
>     [javac] Compiling 134 source files to /home/michaeln/HOL/examples/lassie/sempre/classes
>     [javac] javac: invalid target release: 1.8
>     [javac] Usage: javac <options> <source files>
>     [javac] use -help for a list of possible options
> ```

I just tested it locally, and PR #879 should fix both of these issues.

**Comment by mn200** [comment]
Please look into why this is failing on the Travis regression test.  (There’s an out-of-memory error after 6 minutes spent on `LassieTestTheory`.) I think this showed up before (_i.e._ it’s not to do with the change in this PR).

**Comment by mn200** [comment]
Err, the change in #879 seems unrelated I mean.

**Pull request merged**
