### PR TITLE
catch failure to disprove and treat as fatal

### PR DESCRIPTION
**Pull request by vo1stv**
Single line change to line 238.
Note to @mn200: if you prefer to have all self-tests incorporated into one file, this is a good opportunity make a request to do so

### CODE REVIEW

**Comment by vo1stv** [comment]
@mn200 I think I've gleaned how to incorporate all tests.  Please include these latest changes in the pull request.

**Comment by vo1stv** [comment]
One last nicety.  I'm happy now.

**Comment by mn200** [comment]
Thanks for putting the tests into one executable.  I agree with Thomas about using `POP_ASSUM` (and `REPEAT`...). If you want to develop more tests, you might also feel free to put all the test-relevant stuff into a sub-directory (and to then add that test directory to the build sequence as well).

**Comment by vo1stv** [comment]
@thtuerk that works.  @mn200 no plans to add more tests within the examples folder - I'm hoping the example helps someone get started with HOL and Predicative Programming without making them wade through too much content.

**Comment by vo1stv** [comment]
Just curious if there is anything further.

I'd like to have this pull request completed since it does fix some errors
in branch master that I discovered during development of the new proofs.

**Comment by mn200** [comment]
No, as you sound happy with its state, I'm happy to merge.  Thanks for your contribution!

**Pull request merged**
