### PR TITLE
Trial

### PR DESCRIPTION
**Pull request by jeremydaw**
(1) EXISTS_LEFT(1)

show_types := true ;
show_assums := true ;
val tho = mk_oracle_thm "test-exists-left"
  ([], ``f x y ==> g x ==> h y ==> p ==> q ==> r``) ;
val th = UNDISCH_ALL tho ;
val fvx = ``x : 'a`` ;
val fvy = ``y : 'b`` ;
val fvz = ``z : 'c`` ;
val fvr = concl th ;
EXISTS_LEFT [fvx] th ;
EXISTS_LEFT [fvy] th ;
val the' = EXISTS_LEFT [fvx, fvy] th ;
val the = EXISTS_LEFT [fvy, fvx] th ;

(2) UNDISCH_TM
val tm = ``a ==> b ==> c ==> d ==> e`` ;
strip_gen_left UNDISCH_TM (ASSUME tm) ;

### CODE REVIEW

**Comment by jeremydaw** [comment]
third commit now included in this is doc for Drule.SIMPLE_EXISTS

I looked at Drule.SIMPLE_CHOOSE as well, and as far as I see, when it works and does something useful it does the same as EXISTS_LEFT1.

Ie it picks a hypothesis at random, and if the free variable given is  only in that hypothesis (and not the conclusion) it does the same as EXISTS_LEFT1.

If the free variable is not in the theorem at all, then it nonetheless quantifies the chosen hypothesis over it.

Otherwise it fails.
val th = mk_thm ([``x = y``, ``x = z``], ``p /\ q``) ;

SIMPLE_CHOOSE (``x``) th ;
SIMPLE_CHOOSE (``y``) th ;
SIMPLE_CHOOSE (``z``) th ;
SIMPLE_CHOOSE (``w``) th ;

EXISTS_LEFT1 (``x``) th ;
EXISTS_LEFT1 (``y``) th ;
EXISTS_LEFT1 (``z``) th ;
EXISTS_LEFT1 (``w``) th ;

**Comment by jeremydaw** [comment]
recent adds:
ASSUME_CONJS: 
t1 /\ ... /\ tn   --->   [t1, ..., tn] |- t1 /\ ... /\ tn  
  constructs a theorem proving conjunction from individual conjuncts         
  
SPEC_UNDISCH_EXL: strips !x, ant ==>, then EXISTS_LEFT for stripped vars

prim_irule_tac : Similar to MATCH_ACCEPT_TAC but   
(1) allows substitution in hypotheses of the supplied theorem          
(2) adds new subgoals for those hypotheses                              
   
irule: similar to MATCH_MP_TAC, but
(1) uses conclusion following more than one ==>                            
(2) where multiple assumptions involve the same variable that is not in     
the conclusion (as y in x = y ==> y = z ==> x = z), collects them  
and existentially quantifies 
(3) hypotheses of the theorem provided also become new subgoals

**Comment by mn200** [comment]
It's probably my fault that it's this way round at all, but if there's one called `irule` (which I like), could you make the other one `prim_irule` rather than `prim_irule_tac` please?

**Comment by jeremydaw** [comment]
done

Jeremy

**Pull request merged**
