### PR TITLE
Turing Machine theory and the start of register machine theory

### PR DESCRIPTION
**Pull request by ejcatt**

### CODE REVIEW

**Comment by marioxcc** [comment]
I suggest that you add the BSD license header to add your files (see “COPYING” in the HOL4 source tree) and wrap long lines (see “Manual/Proofstyle/style.md”). This is necessary to clarify license status because [by default, works are “all rights reserved”](https://www.gnu.org/licenses/license-list.html#NoLicense).

Note: I am not a maintainer and I do not have write access to the HOL4 repository; therefore this is _unofficial_ advice.

**Comment by thtuerk** [comment]
@ejcatt Thank you for using HOL 4 and sharing your work.

I have been working with HOL 4 since 2005 now. However, I'm unaware of the COPYING file @marioxcc mentions. I know that some HOL 4 files carry a BSD licence header, but rather few. In contrast to @marioxcc, I believe the central copyright notice is sufficient. Anyhow, this would be a separate discussion, not something for a pull request.

The style guide mentioned is very useful for writing clear, robust, easy to maintain proofs. In my personal opinion, your proof scripts might become clearer and easier to read by adding extra line breaks. However, this is my personal opinion and the style guide is only a guide. Especially in the examples directory, there are a lot of different styles used.

@ejcatt I have not read your pull request carefully and I won't merge it in any case, since I'm not one of the maintainers of HOL 4. Anyhow, at the brief glance I had, it looks interesting. Thank you.

**Comment by marioxcc** [comment]
I meant the file called “COPYRIGHT”. I mistakenly referred to it as “COPYING”.

**Comment by mn200** [comment]
I am making some tweaks (syntactic tidying) to this PR but on a local branch called `pr/506` (see for example 430da2038). I think/hope that when this is merged, GitHub will see this PR as done.

**Pull request merged**
