### PR TITLE
adding of example project regexpemit

### PR DESCRIPTION
**Pull request by marcuslindner**
Dear HOL team,

The following additions are an example project on regular expressions and code exporting that was created by us as part of Thomas Türk's course on interactive theorem proving at KTH. He helped us along the way with discussions and patience.

Could you please review and consider our example project for addition to the official HOL repository? We are looking forward to your feedback and answer.

Best Regards,
Marcus and Andreas Lindner

### CODE REVIEW

**Comment by thtuerk** [comment]
Hi Andreas, Marcus,

I just had a brief glance at this pull request. I will have a closer look soon. However, we discussed the content mostly last summer already, I believe.

For merging here, could you please clean up the history including rebasing? It would also be good to remove the `.gitignore` file.

**Comment by mn200** [comment]
This should be merged into `examples/formal-languages` please, presumably even `examples/formal-languages/regular`.

**Comment by mn200** [comment]
A new sub-directory `regular/regular-play` ?

**Comment by konrad-slind** [comment]
I'm agreeable to that. --Konrad.

**Comment by marcuslindner** [comment]
Now we've finished cleaning and created a branch for this: "regular-play_clean".

What's the best way to do this? We don't find an option to change the branch here and we think it might cause problems when we shift around the old branch pointer onto the new branch. Should we close this pull request and create a new one with the new branch? Or shift the branch pointer around? Or is there some other option we're missing?

**Comment by xrchz** [comment]
Why not just use the same branch name as for this PR? (I don't think the branch name matters much.)

**Comment by marcuslindner** [comment]
Btw: the failing build comes from another part of HOL. We noticed the same output locally when we take your master branch and build with selftest level 2. But if we build with the default level and then build our Project, it works.

**Comment by marcuslindner** [comment]
@xrchz Thanks! Then we shift it around - let's see what happens.

**Comment by andreaslindner** [comment]
I wanted to reanimate this pull request again, maybe it became forgotten. The current state (from Jul 9) incorporates all your comments. Shall we move on from there?

**Comment by mn200** [comment]
Thanks for your contribution.  I will fix any problems caused by our delay in getting this merged!

**Comment by andreaslindner** [comment]
Thanks for the fixes and merging!

**Comment by andreaslindner** [comment]
>           Thanks for your contribution.  I will fix any problems caused by our delay in getting this merged!

Thanks for the fixes and merging!

**Pull request merged**
