### PR TITLE
AKS mechanisation

### PR DESCRIPTION
**Pull request by jhlchan**
Import from  my PhD thesis work.

### CODE REVIEW

**Comment by mn200** [comment]
Looks good. Two comments:

- please remove `OPTIONS = QUIT_ON_FAILURE` from all the Holmakefiles (this is no longer required)
- please write an addition to the release notes file (`doc/next-release.md`) describing the example

**Comment by mn200** [comment]
In the AKS Holmakefile, you should specify a particular target to represent the culmination of the work.  (Otherwise Holmake won't build anything at all because there are no default targets in the AKS directory.) I'd suggest putting something like the following in:

```
.PHONY: all
all: theories/AKScleanTheory.uo
```

**Comment by mn200** [comment]
I notice that if all you need is `AKScleanTheory` then `AKSmachineTheory` isn't built.  Is that file supposed to be present?

**Comment by mn200** [comment]
Conversely, in the `algebra` example, you don't have a `Holmakefile` at all.  I'd suggest creating one that looks like
```
CLINE_OPTIONS = -r
INCLUDES = field finitefield group lib linear monoid polynomial ring
```
That way, if someone does `Holmake` in `examples/algebra` everything is built.  At the moment, nothing at all happens.

**Comment by binghe** [comment]
Hi, nice work. Where can I find your thesis? I’d like to read it.

**Comment by mn200** [comment]
See: https://openresearch-repository.anu.edu.au/handle/1885/177195

**Comment by mn200** [comment]
Thanks for this!

**Pull request merged**
