### PR TITLE
Monad

### PR DESCRIPTION
**Pull request by jeremydaw**
can do definition (rather than specification) of LUNFOLD using option monad functions; 
define LTL_HD as it's "inverse" to LUNFOLD

### CODE REVIEW

**Comment by xrchz** [comment]
This is pretty cool! Can you get it to work on -expk?

**Comment by jeremydaw** [comment]
Well, I think I've got a change to make it work in both.

It's a pain that both kernels behave differently, I wonder if it is easy 
to fix this.

**Comment by xrchz** [comment]
I agree that the kernels ought to behave the same. While they don't, though, the instruction to the user is to not depend on generated names (e.g., rename variables first if you have to refer to them).

**Comment by jeremydaw** [comment]
Have renamed variables, in essence, using X_GEN_TAC, which I didn't find earlier.  (A much better solution, I agree).

**Pull request merged**
