### PR TITLE
Automatic proofs that datatypes are countable

### PR DESCRIPTION
**Pull request by talsewell**
Some setup theory and a library that automatically proves that
datatypes defined in the TypeBase are countable.

I think I put the theory in the right place, it's unclear though whether
the relevant code belongs under 'more_theories'.

### CODE REVIEW

**Comment by mn200** [comment]
Thanks!

**Comment by mn200** [comment]
If you're going to appeal to `bossLib` or `listTheory`, then you definitely need to be in `pred_set/src/more_theories`, and so too do your tests.   As _per_ de7a160.

**Comment by xrchz** [comment]
I thought there was a library for this in examples, but I can't find it any
more. Was it moved/deleted?

**Comment by mn200** [comment]
Commit f55fd784a053e12 mentions removal of something called `countable` (“unused and untested” apparently), so I guess that may have been this.

**Pull request merged**
