### PR TITLE
`topologyTheory` (new), `metricTheory` and `rich_topologyTheory` in release notes

### PR DESCRIPTION
**Pull request by binghe**
Hi,

as requested by Michael Norrish, I have put a paragraph into next release notes on what I have ﻿done for HOL4's new Topology Theory scripts. Feel free to revise the texts.

---
Chun Tian

### CODE REVIEW

**Comment by mn200** [comment]
Insert “theory” after this phrase:

> Now HOL4 has a rather complete Elementary Topology in Euclidean Space 

?

Or after “Topology”.  Otherwise it sounds as if you are claiming that HOL4 has a topology itself... :)

**Comment by AndreasLoow** [comment]
Micro-suggestion: You might want to replace "metric-related stuff" with "metric-related results", "metric-dependent parts" or something similar.

**Comment by binghe** [comment]
thanks, what about now?

**Comment by mn200** [comment]
Fantastic — thanks!

**Pull request merged**
