### PR TITLE
Define SHA-256 (part of the SHA-2 standard) and translate it for cv compute

### PR DESCRIPTION
**Pull request by xrchz**
As with Keccak (SHA-3), this is one of the cryptographic algorithms used in the Ethereum virtual machine.

### CODE REVIEW

**Review by mn200 — CHANGES_REQUESTED** [review]
Please put this directory into the build sequence (by adjusting `src/parallel_builds/core/Holmakefile`)

**Comment by xrchz** [comment]
> Please put this directory into the build sequence (by adjusting `src/parallel_builds/core/Holmakefile`)

This is done

**Comment by mn200** [comment]
It's not building because your Holmakefile needs an `INCLUDES` line pointing at the directory with `cv_transLib` etc.  (The reason in turn is that `build` is doing everything in parallel so needs accurate directory dependency info within post-boss directories.)

**Comment by xrchz** [comment]
Thanks I've added that Holmakefile now.

**Review by mn200 — APPROVED** [review]

**Pull request merged**
