### PR TITLE
relaxing type constraint for THEN and THENL

### PR DESCRIPTION
**Pull request by jeremydaw**
to permit
val THEN           : list_tactic * tactic -> list_tactic
val THENL          : list_tactic * tactic list -> list_tactic
as well as the usual types

also EVERY_LT for list of list-tactics

### CODE REVIEW

**Comment by xrchz** [comment]
Cool. I'd like to see `CONJ_ASMx_TAC` implemented more simply in terms of `USE_SG_THEN` as part of this pull request.

**Comment by jeremydaw** [comment]
Done - also the help file for USE_SG_THEN now seems OK

**Comment by xrchz** [comment]
Thanks. Only problem now is it seems to break the build on expk (https://travis-ci.org/HOL-Theorem-Prover/HOL/jobs/45588681).

**Comment by jeremydaw** [comment]
Added infix THEN_LT in Tactic.sml.  Not sure why needed, since builds OK here without it.  Also apparently not needed for THEN in Tactic.sml.  Hoping this works now.

**Comment by jeremydaw** [comment]
Hi Ramana,

You've been pretty prompt about looking at and considering my 
contributions - thanks for that.

Except for https://github.com/HOL-Theorem-Prover/HOL/pull/218
on that one, no action, no critical comments, no queries, either.
What about that one?

Cheers,

Jeremy Dawson

**Pull request merged**
