### PR TITLE
Trial

### PR DESCRIPTION
**Pull request by jeremydaw**
needing to do some stuff with rationals, found existing proofs seemed more complicated than they need be

### CODE REVIEW

**Comment by xrchz** [comment]
This looks great! Document the new functions?

**Comment by jeremydaw** [comment]
OK I'll do that but maybe not for a couple of weeks, since I'm 
travelling much of next week and have the following week off

Jeremy

**Comment by jeremydaw** [comment]
OK, I've done doc pages for the new functions PART_MATCH_A and REWR_CONV_A
Would it make sense to do the same things for HO_PART_MATCH and HO_REWR_CONV ?

**Comment by xrchz** [comment]
Yes certainly, if you're happy to.

**Comment by jeremydaw** [comment]
OK, will do, but it will have to wait a week or more

**Comment by xrchz** [comment]
I think you can just open another pull request later :)

**Pull request merged**
